### ISSUE TITLE
PSAI GUID/version discrepancy

### ISSUE THREAD

**Issue by ant3869** [dfinke/PShell-AI#2]
Looks like there is a discrepancy, unless I just did something wrong.

The PSAI module is installed correctly with version 0.1.0, but its GUID is 68662d19-a8f1-484f-b1b7-3bf0e8a436df.
The PShell-AI module is expecting PSAI with GUID 081ce7b4-6e63-41ca-92a7-2bf72dbad018.

cheers

**Comment by dfinke** [comment]
Thank you @ant3869 for trying PShell-AI and reporting the issue.

I tool the `guid` from my original `PowerShellAI ` module instead ot my `PSAI` module.

I will add tests of the psd1 to catch that before publishing.

**Comment by ant3869** [comment]
Ah, right on. Glad I was able to help out, thanks for all the hard work, great stuff btw.
